name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up virtual environment and install dependencies
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the environment
        pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install required packages

    - name: Run Makefile commands
      run: |
        source venv/bin/activate  # Activate the virtual environment
        make all  # This will run the "all" target in the Makefile, which triggers all the steps
